spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:'
    username: username
    password: password password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
