spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data;AUTO_SERVER=TRUE
    username: username
    password: password password
  jpa:
    hibernate:
      ddl-auto: validate
